# Generated by Django 2.2.14 on 2020-08-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200803_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_list',
        ),
        migrations.AddField(
            model_name='contactlist',
            name='contacts',
            field=models.ManyToManyField(to='contacts.Contact'),
        ),
    ]
